# Generated by Django 5.2 on 2025-04-06 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0003_alter_profile_name_alter_profile_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=32)),
                ('short_name', models.CharField(blank=True, max_length=32, null=True)),
                ('region', models.CharField(max_length=32)),
                ('industry', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('inprogress', 'In Progress'), ('done', 'Done')], default='waiting', max_length=10)),
                ('region', models.CharField(blank=True, max_length=32, null=True)),
                ('industry', models.CharField(blank=True, max_length=32, null=True)),
                ('direction', models.CharField(blank=True, max_length=32, null=True)),
                ('budget', models.FloatField(blank=True, null=True)),
                ('publish_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('days', models.IntegerField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.profile')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationHasUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('participant', 'Participant')], max_length=16)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.profile')),
            ],
            options={
                'unique_together': {('organization', 'user')},
            },
        ),
    ]
