# Generated by Django 5.2 on 2025-04-06 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0003_alter_profile_name_alter_profile_password_and_more'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('data', models.BinaryField()),
                ('type', models.CharField(choices=[('file', 'File'), ('photo', 'Photo'), ('voice', 'Voice')], default='file', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='authorization.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='authorization.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.startup')),
            ],
        ),
        migrations.CreateModel(
            name='TopicMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('got_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('private', 'Private'), ('topic', 'Topic'), ('startup', 'Startup')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('startup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.startup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.profile')),
                ('private_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger.privatemessage')),
                ('topic_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger.topicmessage')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateMessageHasFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.file')),
                ('private_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.privatemessage')),
            ],
            options={
                'unique_together': {('private_message', 'file')},
            },
        ),
        migrations.CreateModel(
            name='TopicMessageHasFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.file')),
                ('topic_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.topicmessage')),
            ],
            options={
                'unique_together': {('topic_message', 'file')},
            },
        ),
    ]
