# Generated by Django 4.2.15 on 2025-04-06 06:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_rename_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.TextField(),
        ),
    ]
