# Generated by Django 5.2 on 2025-04-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_rename_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.TextField(),
        ),
    ]
