# Generated by Django 4.2.15 on 2025-04-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_alter_profile_name_alter_profile_password_and_more'),
        ('authorization', '0003_token_alter_profile_email_alter_profile_name_and_more'),
    ]

    operations = [
    ]
